### ISSUE TITLE
Feature request: edit `title` and `authors` from web UI

### ISSUE THREAD

**Issue by aviatesk** [akawashiro/jendeley#187]
Might be nice since otherwise we don't have a way to specify those information for PDFs that don't have IDs.

**Comment by akawashiro** [comment]
I agree. But this need quite a lot of implementation including DB schema change. Please use tag for now.

**Comment by akawashiro** [comment]
https://github.com/akawashiro/jendeley/pull/245 resolves this.

**Comment by aviatesk** [comment]
Great, thanks!
