### ISSUE TITLE
some doi suffixes have a slash

### ISSUE THREAD

**Issue by ocxtal** [akawashiro/jendeley#258]
I tried to register [10.1093/nar/27.2.573](https://doi.org/10.1093/nar/27.2.573), which was downloaded to my local and renamed to `27-2-573 [jendeley doi 10_1093_nar_27_2_573].pdf`, to jendeley v2.0.7, and found it failed with `There is no document identifiers in 27-2-573 [jendeley doi 10_1093_nar_27_2_573].pdf`.

I took a glance at the code and found there are a lot of regex patterns for different doi suffix styles in `getDocIDManuallyWritten`. Is it fine to add a new regex pattern for this kind of dois? or (parhaps) are you thinking of rewriting the patterns into a common one?

**Comment by akawashiro** [comment]
Thank you for your report.

Because I have no good idea to parse DOI in more elegant way, we should add a new regex pattern for this kind DOI. I have started to resolve this problem on https://github.com/akawashiro/jendeley/pull/259.

**Comment by ocxtal** [comment]
Thank you very much!! 🙌 🙌 🙌 ありがとうございます、とても助かります

**Comment by ocxtal** [comment]
ありがとうございます! 🙇

**Comment by akawashiro** [comment]
@ocxtal Can I close this? If you have any other problem, feel fee to reopen or make another issue.
